[package]
name = "fekin"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33"

[profile.dev]
opt-level = 3
codegen-units = 1
lto = "thin"
debug = 0
debug-assertions = false
overflow-checks = false
